### ISSUE TITLE
json tests fail

### ISSUE THREAD

**Issue by brycv** [kristapsdz/sblg#21]
I am attempting to update the OpenBSD port to sblg 0.5.12 and the json tests seem to be failing. It looks like files are missing and apparently jq is now required for tests?

=== JSON tests === 
/bin/sh: jq: not found
sblg: regress/json/*.xml: No such file or directory
*** Error 1 in /usr/ports/pobj/sblg-0.5.12/sblg-0.5.12 (Makefile:286 'regress': @tmp=`mktemp` ;  MALLOC_OPTIONS=S ;  echo "=== standalone te...)
*** Error 2 in . (/usr/ports/infrastructure/mk/bsd.port.mk:3102 '/usr/ports/pobj/sblg-0.5.12/.test_done': @cd /usr/ports/pobj/sblg-0.5.12/sb...)
*** Error 2 in /usr/ports/www/sblg (/usr/ports/infrastructure/mk/bsd.port.mk:2710 'test': @lock=sblg-0.5.12;  export _LOCKS_HELD=" sblg-0.5....)

**Comment by kristapsdz** [comment]
That's true about `jq`, yes, it's a requirement for the tests now. There was an issue opened earlier about some tests missing from the release and it's been fixed in the main repo, but not in a version yet.  I'm going to tag out another release in a day or two with those and many more in it as well, if you can wait!  Thanks again for maintaining the port for sblg.

**Comment by kristapsdz** [comment]
(I'll close out the issue with the next version that will fix this.)

**Comment by kristapsdz** [comment]
Fixed and versioned!
